#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
PYTHON="${PYTHON:-python3}"
"$PYTHON" scripts/validate_examples.py
"$PYTHON" tests/test_adl_v02_canonical_shape.py
"$PYTHON" tests/test_adl_v02_source_boundary.py
"$PYTHON" tests/test_adl_v02_conformance_profiles.py
"$PYTHON" tests/test_adl_v02_runtime_deployment.py
"$PYTHON" tests/test_adl_v02_permission_policy.py
"$PYTHON" tests/test_adl_v02_tool_contract.py
"$PYTHON" tests/test_adl_v02_eval_gate_completion.py
"$PYTHON" tests/test_adl_v02_examples_diagnostics.py
"$PYTHON" tests/test_provider_compatibility_cli.py
"$PYTHON" tests/test_provider_adapter_codegen_plan.py
"$PYTHON" tests/test_validation_guidance.py
"$PYTHON" tests/test_tool_execution.py
"$PYTHON" tests/test_cli_usage_matrix.py
"$PYTHON" tests/test_readiness_bundle.py
"$PYTHON" tests/test_adapter_readiness.py
"$PYTHON" tests/test_mcp_adapter_contract.py
"$PYTHON" tests/test_mcp_adapter_error_semantics.py
"$PYTHON" tests/test_mcp_adapter_aggregation.py
"$PYTHON" tests/test_mcp_adapter_source_check.py
"$PYTHON" tests/test_mcp_server_resolution.py
"$PYTHON" tests/test_mcp_capability_policy.py
"$PYTHON" tests/test_mcp_readiness_evidence.py
"$PYTHON" tests/test_mcp_readiness_release.py
"$PYTHON" tests/test_mcp_runtime_handoff_package.py
"$PYTHON" tests/test_agent_spec_compatibility.py
"$PYTHON" tests/test_a2a_agent_card_export.py
"$PYTHON" tests/test_agent_skill_export.py
"$PYTHON" tests/test_rap_bridge_report.py
"$PYTHON" tests/test_rap_provider_handoff_summaries.py
"$PYTHON" tests/test_eve_compatibility.py
"$PYTHON" tests/test_ap2_x402_mandate_report.py
"$PYTHON" tests/test_prosumer_builder_plan.py
"$PYTHON" tests/test_static_export_target_parity.py
"$PYTHON" tests/test_protected_docs_package.py
"$PYTHON" tests/test_public_blog_draft.py
"$PYTHON" tests/test_open_spec_review_intake.py
"$PYTHON" tests/test_prosumer_builder_static_export.py
"$PYTHON" tests/test_starter_code_plan.py
"$PYTHON" tests/test_starter_code_generation_beta.py
"$PYTHON" tests/test_starter_package_execution_smoke_beta.py
"$PYTHON" tests/test_provider_adapter_generated_code_sandbox_beta.py
"$PYTHON" tests/test_rap_bridge_local_dry_run.py
"$PYTHON" tests/test_local_runner_plugin_interface.py
"$PYTHON" tests/test_local_runtime_prototype.py
"$PYTHON" tests/test_provider_sandbox_prototype.py
"$PYTHON" tests/test_live_mcp_devnet_handoff_prototype.py
"$PYTHON" tests/test_surfpool_validator_lane.py
"$PYTHON" tests/test_docker_testing_lane.py
"$PYTHON" tests/test_coolify_staging_lane.py
"$PYTHON" tests/test_beta_operator_control_harness.py
"$PYTHON" tests/test_beta_release_readiness.py
"$PYTHON" tests/test_beta_local_runtime_rc_gate.py
"$PYTHON" tests/test_beta_operator_dry_run_package.py
"$PYTHON" tests/test_beta_review_ui.py
"$PYTHON" tests/test_beta_operator_decision_package.py
"$PYTHON" tests/test_beta_activation_preflight_gate.py
"$PYTHON" tests/test_beta_activation_rehearsal_package.py
"$PYTHON" tests/test_beta_activation_acceptance_bundle.py
"$PYTHON" tests/test_beta_release_handoff_archive.py
"$PYTHON" tests/test_beta_reviewer_walkthrough_smoke.py
"$PYTHON" tests/test_beta_release_verification_cli.py
"$PYTHON" tests/test_beta_release_candidate_bundle.py
"$PYTHON" tests/test_beta_release_archive_assembler.py
"$PYTHON" tests/test_beta_onboarding_quickstart_package.py
"$PYTHON" tests/test_beta_reviewer_acceptance_checklist_package.py
"$PYTHON" tests/test_beta_e2e_acceptance_smoke_runner.py
"$PYTHON" tests/test_beta_runtime_activation_evidence_gate.py
"$PYTHON" tests/test_beta_runtime_activation_canary_runner.py
"$PYTHON" tests/test_beta_runtime_service_activation_approval_packet.py
"$PYTHON" tests/test_beta_runtime_service_activation_evidence_gate.py
"$PYTHON" tests/test_beta_runtime_service_activation_live_run_gate.py
"$PYTHON" tests/test_beta_runtime_service_wrapper_activation_smoke.py
"$PYTHON" tests/test_beta_runtime_service_wrapper_operator_run_package.py
"$PYTHON" tests/test_beta_bounded_external_service_activation_gate.py
"$PYTHON" tests/test_beta_external_service_activation_micro_gate.py
"$PYTHON" tests/test_beta_external_service_approval_intake.py
"$PYTHON" tests/test_beta_external_service_approval_authorization.py
"$PYTHON" tests/test_coolify_devnet_public_demo.py
"$PYTHON" tests/test_payment_dry_run_receipt.py
"$PYTHON" tests/test_adl_validation_ui.py
